repos:
# Hooks are executed in given order

    # Use tools from virtual environment
-   repo: local
    hooks:

    # Sort imports
    -   id: isort
        name: isort
        args: ["--profile", "black", "--filter-files"]
        entry: isort
        language: python
        types: [python]
        additional_dependencies: ['isort']
        language_version: python3.9

    # Code Formatter, PEP8
    -   id: black
        name: black
        entry: black
        language: python
        types: [python]
        additional_dependencies: ['black']
        language_version: python3.9

    # Check the style and quality of some
    # python code (pep8, pyflakes, third party plugins etc.)
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      types: [python]
      additional_dependencies: ['flake8']
      language_version: python3.9
