repos:
-   repo: local
    hooks:
    # Use isort from virtual environment
    -   id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
        additional_dependencies: ['isort']
        language_version: python3.9

    # Use black from virtual environment
    -   id: black
        name: black
        entry: black
        language: python
        types: [python]
        additional_dependencies: ['black']
        language_version: python3.9

    # Use flake8 from virtual environment
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      types: [python]
      additional_dependencies: ['flake8']
      language_version: python3.9
