# Partly a source: https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/

version: '3.7'

services:
  web:
    build:
      # Note: context is supposed to be 'kiosk',
      # but since Pipfile exists outside of 'kiosk' dir,
      # we need to use parent directory.
      context: kiosk
      dockerfile: prod.Dockerfile
    # use Django's built-in server in development
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn kiosk.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./kiosk/:/usr/src/app/
    # expose: Now, port 8000 is only exposed internally, to other Docker services.
    # The port will no longer be published to the host machine.
    expose:
      - 8000
#    ports:
#      - 8000:8000
    env_file:
      - kiosk/kiosk/settings/.env.prod

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    depends_on:
      - web

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
    postgres_data:
