# Partly a source: https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/

version: '3.7'

services:
  web:
    build:
      context: ""
      dockerfile: Dockerfile
    # use Django's built-in server in development
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./kiosk/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    #env_file:
    #  - kiosk/kiosk/settings/.env.prod

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=kiosk
      - POSTGRES_PASSWORD=kiosk
      - POSTGRES_DB=kioskdb
      - DB_HOST=db
    depends_on:
      - web

volumes:
    postgres_data:
