version: '3.7'

services:
  web:
    build:
      context: ""
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./kiosk/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - kiosk/kiosk/settings/.env.dev

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=kiosk
      - POSTGRES_PASSWORD=kiosk
      - POSTGRES_DB=kioskdb

volumes:
    postgres_data:

#
#
#
#
#version: '3.7'
#
#services:
#  web:
#    build:
#      context: ./kiosk
#      dockerfile: Dockerfile.prod
#    image: 108408647134.dkr.ecr.us-east-1.amazonaws.com/django-ec2:web
#    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
#    volumes:
#      - static_volume:/home/app/web/staticfiles
#      - media_volume:/home/app/web/mediafiles
#    expose:
#      - 8000
#    env_file:
#      - ./.env.prod
#  nginx-proxy:
#    container_name: nginx-proxy
#    build: nginx
#    image: 108408647134.dkr.ecr.us-east-1.amazonaws.com/django-ec2:nginx-proxy
#    restart: always
#    ports:
#      - 443:443
#      - 80:80
#    volumes:
#      - static_volume:/home/app/web/staticfiles
#      - media_volume:/home/app/web/mediafiles
#      - certs:/etc/nginx/certs
#      - html:/usr/share/nginx/html
#      - vhost:/etc/nginx/vhost.d
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#    depends_on:
#      - web
#  nginx-proxy-letsencrypt:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    env_file:
#      - ./.env.prod.proxy-companion
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - certs:/etc/nginx/certs
#      - html:/usr/share/nginx/html
#      - vhost:/etc/nginx/vhost.d
#      - acme:/etc/acme.sh
#    depends_on:
#      - nginx-proxy
#
#volumes:
#  static_volume:
#  media_volume:
#  certs:
#  html:
#  vhost:
#  acme: