# Generated by Django 4.1 on 2022-08-30 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forms", "0001_initial"),
        ("managers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kiosk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kiosk_form",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="forms.kioskform",
                    ),
                ),
                (
                    "kiosk_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="managers.kioskmanager",
                    ),
                ),
            ],
        ),
    ]
