# Generated by Django 4.1 on 2022-09-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("input", "Input"),
                    ("textarea", "textarea"),
                    ("select", "Select"),
                    ("checkbox", "Checkbox"),
                    ("radio", "Radio"),
                ],
                default="input",
                max_length=8,
            ),
        ),
    ]
