# Generated by Django 4.1 on 2022-09-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataModelEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiver_email", models.EmailField(max_length=256)),
                ("receiver_name", models.CharField(max_length=64)),
                ("subject", models.CharField(max_length=50)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("C", "Created"),
                            ("Q", "Queue"),
                            ("S", "Sent"),
                            ("E", "Error"),
                        ],
                        default="C",
                        max_length=1,
                    ),
                ),
                ("error_message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
